name: Keep Supabase Alive

on:
  schedule:
    # بيشتغل الساعة 12 بالليل كل يوم سبت وتلات
    - cron: "0 0 * * 2,6"
  workflow_dispatch: # عشان تقدر تشغله يدوي للتجربة

jobs:
  ping_supabase:
    runs-on: ubuntu-latest
    steps:
      - name: Send a request to Supabase
        run: |
          curl -X GET "${{ secrets.SUPABASE_URL }}/rest/v1/students_view?select=id&limit=1" \
          -H "apikey: ${{ secrets.SUPABASE_ANON_KEY }}" \
          -H "Authorization: Bearer ${{ secrets.SUPABASE_ANON_KEY }}"
